# Generated by Django 5.2.7 on 2025-10-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('waste_collector', 'Waste Collector'), ('kitchen_manager', 'Community Kitchen Manager'), ('distributor', 'Distributor'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
