# Generated by Django 5.2.7 on 2025-10-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_phone_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastecollection',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
